version: '3.8'
services:
  tile38:
    image: tile38/tile38:latest
    ports:
      - "9851:9851"
    volumes:
      - tile38_data:/data
    command: [ "tile38-server", "-p", "9851" ]
    healthcheck:
      test: [ "CMD", "tile38-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: delivery_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  tile38_data:
  postgres_data: